Repository f1nal3/Juniorgram, pull requests merged in 2021-11, with the labels that each got.

#455 CV fix
  DataAccess/DataAccess.Postgre/PostgreRepositoryManager.hpp
Labels: Back

#458 Create Setup server on localhost.md
  Docs/Setup server on localhost.md
  README.md
Labels: documentation

#459 Chat page shortcuts
  Client/Client.Qt/Widgets/ChannelListWidget.cpp
  Client/Client.Qt/Widgets/ChannelListWidget.hpp
  Client/Client.Qt/Widgets/InputFields.cpp
  Client/Client.Qt/Widgets/InputFields.hpp
  Client/Client.Qt/Widgets/ListWidget.cpp
  Client/Client.Qt/Widgets/ListWidget.hpp
  Client/Client.Qt/Widgets/TextEdit.cpp
Labels: Front

#460 Notification bar
  Client/Client.Qt/Application.cpp
  Client/Client.Qt/Application.hpp
  Client/Client.Qt/ConnectionManager.cpp
Labels: enhancement, Front

#461 Login kick fix
  Server/Server.Core/Server.Core.Static/Server.cpp
  Server/Server.Core/Server.Core.Static/Server.hpp
Labels: Back

#457 Front leaving and deleting a channel
  Client/Client.Qt/ConnectionManager.cpp
  Client/Client.Qt/Pages/ChannelListPage.cpp
  Client/Client.Qt/Pages/ChannelListPage.hpp
  Client/Client.Qt/Pages/ChatPage.cpp
  Client/Client.Qt/Pages/ChatPage.hpp
  Client/Client.Qt/Widgets/ChannelBar.cpp
  Client/Client.Qt/Widgets/ChannelBar.hpp
  Client/Client.Qt/Widgets/ChannelListWidget.cpp
  Client/Client.Qt/Widgets/ChatWidget.cpp
  Client/Client.Qt/Widgets/ChatWidget.hpp
  DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
Labels: Front, Back
