Repository f1nal3/Juniorgram, pull requests merged in 2021-10, with the labels that each got.

#421 Message spaces trimming
  Server/Server.Core/Server.Core.Static/Server.cpp
  Utility/Utility.Public/CMakeLists.txt
  Utility/Utility.Public/Include/Utility/Utility.hpp
Labels: Back

#436 Windows server concurrency fix
  Network/Public/Include/Network/Connection.hpp
Labels: bug, Back

#420 Repository manager implementation
  DataAccess/DataAccess.Postgre/1PostgreRepository.cpp
  DataAccess/DataAccess.Postgre/1PostgreRepository.hpp
  DataAccess/DataAccess.Postgre/CMakeLists.txt
  DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
  DataAccess/DataAccess.Postgre/PostgreRepositories.hpp
  DataAccess/DataAccess.Postgre/PostgreRepositoryManager.hpp
  DataAccess/Public/CMakeLists.txt
  DataAccess/Public/Include/DataAccess/IServerRepositories.hpp
  Server/Server.Core/Server.Core.Static/CMakeLists.txt
  Server/Server.Core/Server.Core.Static/Server.cpp
  Server/Server.Core/Server.Core.Static/Server.hpp
  Server/Server.Exec/MainServer.cpp
Labels: Back

#428 Message editing on server side
  DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
  DataAccess/DataAccess.Postgre/PostgreRepositories.hpp
  DataAccess/Public/Include/DataAccess/IRepository.hpp
  DataAccess/Public/Include/DataAccess/IServerRepositories.hpp
  Network/Public/Include/Network/Message.hpp
  Network/Public/Include/Network/SerializationHandler.hpp
  Server/Server.Core/Server.Core.Static/Server.cpp
  Utility/Utility.Public/Include/Utility/Utility.hpp
Labels: enhancement, Back
