Repository f1nal3/Juniorgram, pull requests merged in 2021-08, with the labels that each got.

#331 Registration returns to login
  Client/Client.Qt/registration.cpp
  DataAccess/Public/CMakeLists.txt
Labels: Front

#328 Fix message storing
  Client/Client.CLI/App.cpp
  Client/Client.CLI/MainClient.cpp
  Client/Client.Core/Client.Core.Static/Client.cpp
  Client/Client.Core/Client.Core.Static/Client.hpp
  Client/Client.Core/Client.Core.Static/ServerInfo.hpp
  Client/Client.Qt/ChatWindow.cpp
  Client/Client.Qt/ChatWindow.hpp
  Client/Client.Qt/ConnectionManager.hpp
  Client/Client.Qt/Widgets/ChannelListWindow.cpp
  Client/Client.Qt/Widgets/ChannelListWindow.hpp
  Client/Client.Qt/Widgets/ChatHistory.cpp
  Client/Client.Qt/Widgets/ChatHistory.hpp
  Client/Client.Qt/Widgets/ChatWidget.cpp
  Client/Client.Qt/Widgets/ChatWidget.hpp
  Client/Client.Qt/Widgets/MessageWidget.hpp
  DataAccess/DataAccess.Debug/FileRepository.cpp
  DataAccess/DataAccess.Debug/FileRepository.hpp
  DataAccess/DataAccess.Postgre/PostgreRepository.cpp
  DataAccess/DataAccess.Postgre/PostgreRepository.hpp
  DataAccess/Public/Include/DataAccess/IRepository.hpp
  Network/Network.Test/BinarySerializeTest.cpp
  Network/Public/Include/Network/Message.hpp
  Network/Public/Include/Network/Primitives.hpp
  Network/Public/Include/Network/SerializationHandler.hpp
  Server/Server.Core/Server.Core.Static/Server.cpp
  Utility/Utility.Public/Include/Utility/Utility.hpp
Labels: Back

#306 Reactions | Documentation
  .clang-format
  Client/Client.Qt/Application.cpp
  Client/Client.Qt/Application.hpp
  Client/Client.Qt/CMakeLists.txt
  Client/Client.Qt/ChatWindow.hpp
  Client/Client.Qt/MainWidget.cpp
  Client/Client.Qt/MainWidget.hpp
  Client/Client.Qt/Settings.cpp
  Client/Client.Qt/Style/Palette.cpp
  Client/Client.Qt/Style/Shadow.hpp
  Client/Client.Qt/Style/Style.cpp
  Client/Client.Qt/Style/Style.hpp
  Client/Client.Qt/Style/StyleBasic.cpp
  Client/Client.Qt/Style/StyleBasic.hpp
  Client/Client.Qt/Style/StyleColor.cpp
  Client/Client.Qt/Style/StyleColor.hpp
  Client/Client.Qt/Style/StyleFont.cpp
  Client/Client.Qt/Style/StyleFont.hpp
  Client/Client.Qt/Style/StyleIcon.cpp
  Client/Client.Qt/Style/StyleIcon.hpp
  Client/Client.Qt/Style/StyleScale.hpp
  Client/Client.Qt/Widgets/BioButton.cpp
  Client/Client.Qt/Widgets/BioButton.hpp
  Client/Client.Qt/Widgets/Buttons.cpp
  Client/Client.Qt/Widgets/Buttons.hpp
  Client/Client.Qt/Widgets/CaptionButton.cpp
  Client/Client.Qt/Widgets/CaptionButton.hpp
  Client/Client.Qt/Widgets/ChannelListWidget.hpp
  Client/Client.Qt/Widgets/ChannelListWindow.cpp
  Client/Client.Qt/Widgets/ChannelListWindow.hpp
  Client/Client.Qt/Widgets/ChatHistory.cpp
  Client/Client.Qt/Widgets/ChatHistory.hpp
  Client/Client.Qt/Widgets/ComboBox.hpp
  Client/Client.Qt/Widgets/FlatButton.hpp
  Client/Client.Qt/Widgets/LogoWidget.hpp
  Client/Client.Qt/Widgets/Menu.cpp
  Client/Client.Qt/Widgets/Menu.hpp
  Client/Client.Qt/Widgets/MenuItem.cpp
  Client/Client.Qt/Widgets/MenuItem.hpp
  Client/Client.Qt/Widgets/MessageWidget.cpp
  Client/Client.Qt/Widgets/MessageWidget.hpp
  Client/Client.Qt/Widgets/PopupWidget.cpp
  Client/Client.Qt/Widgets/PopupWidget.hpp
  Client/Client.Qt/Widgets/ReactionLayout.cpp
  Client/Client.Qt/Widgets/ReactionLayout.hpp
  Client/Client.Qt/Widgets/ScrollArea.cpp
  Client/Client.Qt/Widgets/TextEdit.hpp
  Client/Client.Qt/Widgets/TitleWidget.cpp
  Client/Client.Qt/Widgets/TitleWidget.hpp
  Client/Client.Qt/login.cpp
  Client/Client.Qt/login.hpp
  Client/Client.Qt/registration.cpp
  Client/Client.Qt/registration.hpp
Labels: Front, documentation, enhancement

#341 Client connection rework
  Client/Client.CLI/App.cpp
  Client/Client.CLI/App.hpp
  Client/Client.CLI/MainClient.cpp
  Client/Client.Core/Client.Core.Static/Client.cpp
  Client/Client.Core/Client.Core.Static/Client.hpp
  Client/Client.Core/Client.Core.Static/ServerInfo.hpp
  Client/Client.Qt/Application.cpp
  Client/Client.Qt/Application.hpp
  Client/Client.Qt/CMakeLists.txt
  Client/Client.Qt/ConnectionManager.cpp
  Client/Client.Qt/ConnectionManager.hpp
  Client/Client.Qt/Widgets/ChannelListWindow.cpp
  Client/Client.Qt/Widgets/ChatWidget.cpp
  Client/Client.Qt/Widgets/MessageWidget.cpp
  Client/Client.Qt/login.cpp
  Client/Client.Qt/login.hpp
  Client/Client.Qt/registration.cpp
Labels: documentation, enhancement, Front

#342 Fix ChannelListWindow
  Client/Client.Qt/Widgets/ChannelListWindow.cpp
  Client/Client.Qt/Widgets/ChannelListWindow.hpp
Labels: bug, Front

#310 Stress tester - WIP
  CMakeLists.txt
  Client/Client.CLI/MainClient.cpp
  PerformanceTest/ArgumentParser.cpp
  PerformanceTest/ArgumentParser.hpp
  PerformanceTest/CMakeLists.txt
  PerformanceTest/SimpleTimer.cpp
  PerformanceTest/SimpleTimer.hpp
  PerformanceTest/Tester.cpp
  PerformanceTest/Tester.hpp
  PerformanceTest/main.cpp
Labels: enhancement, Technical debt, tests

#344 Connection signal/slots in Client.Qt
  Client/Client.Qt/Application.hpp
  Client/Client.Qt/ChatWindow.hpp
  Client/Client.Qt/ConnectionManager.cpp
  Client/Client.Qt/ConnectionManager.hpp
  Client/Client.Qt/MainWidget.hpp
  Client/Client.Qt/Widgets/ChannelListWidget.hpp
  Client/Client.Qt/Widgets/ChannelListWindow.cpp
  Client/Client.Qt/Widgets/ChannelListWindow.hpp
  Client/Client.Qt/login.hpp
  Client/Client.Qt/registration.cpp
  Client/Client.Qt/registration.hpp
Labels: documentation, enhancement, Front

#348 Loading spinner and documentation
  Client/Client.Qt/CMakeLists.txt
  Client/Client.Qt/ConnectionManager.hpp
  Client/Client.Qt/MainWidget.cpp
  Client/Client.Qt/Style/Palette.cpp
  Client/Client.Qt/Style/Palette.hpp
  Client/Client.Qt/Style/StyleBasic.cpp
  Client/Client.Qt/Style/StyleBasic.hpp
  Client/Client.Qt/Widgets/AbstractButton.hpp
  Client/Client.Qt/Widgets/ChannelListWidget.cpp
  Client/Client.Qt/Widgets/ChannelListWidget.hpp
  Client/Client.Qt/Widgets/ChannelListWindow.cpp
  Client/Client.Qt/Widgets/ChannelListWindow.hpp
  Client/Client.Qt/Widgets/InputFields.cpp
  Client/Client.Qt/Widgets/InputFields.hpp
  Client/Client.Qt/Widgets/LoadingSpinner.cpp
  Client/Client.Qt/Widgets/LoadingSpinner.hpp
  Client/Client.Qt/Widgets/LogoWidget.cpp
  Client/Client.Qt/Widgets/LogoWidget.hpp
  Client/Client.Qt/Widgets/Page.cpp
  Client/Client.Qt/Widgets/Page.hpp
  Client/Client.Qt/Widgets/ScrollArea.hpp
  Client/Client.Qt/Widgets/TitleWidget.hpp
  Client/Client.Qt/login.cpp
  Client/Client.Qt/login.hpp
  Client/Client.Qt/registration.cpp
  Client/Client.Qt/registration.hpp
Labels: documentation, Front

#355 Client.Qt refactoring
  Client/Client.Qt/Application.cpp
  Client/Client.Qt/Application.hpp
  Client/Client.Qt/CMakeLists.txt
  Client/Client.Qt/ConnectionManager.hpp
  Client/Client.Qt/MainWidget.cpp
  Client/Client.Qt/MainWidget.hpp
  Client/Client.Qt/Pages/ChannelListPage.cpp
  Client/Client.Qt/Pages/ChannelListPage.hpp
  Client/Client.Qt/Pages/ChatPage.cpp
  Client/Client.Qt/Pages/ChatPage.hpp
  Client/Client.Qt/Pages/LoginPage.cpp
  Client/Client.Qt/Pages/LoginPage.hpp
  Client/Client.Qt/Pages/RegistrationPage.cpp
  Client/Client.Qt/Pages/RegistrationPage.hpp
  Client/Client.Qt/Style/Palette.cpp
  Client/Client.Qt/Style/Palette.hpp
  Client/Client.Qt/Style/StyleBasic.cpp
  Client/Client.Qt/Style/StyleBasic.hpp
  Client/Client.Qt/Style/StyleFont.hpp
  Client/Client.Qt/Style/StyleIcon.hpp
  Client/Client.Qt/Style/StyleIcons.cpp
  Client/Client.Qt/Style/StyleIcons.hpp
  Client/Client.Qt/Style/StyleTypes.hpp
  Client/Client.Qt/Style/StyleWidgets.cpp
  Client/Client.Qt/Style/StyleWidgets.hpp
  Client/Client.Qt/Style/Styles.hpp
  Client/Client.Qt/Widgets/AbstractButton.cpp
  Client/Client.Qt/Widgets/Buttons.hpp
  Client/Client.Qt/Widgets/ChannelListWidget.cpp
  Client/Client.Qt/Widgets/ChannelListWidget.hpp
  Client/Client.Qt/Widgets/ChatHistory.hpp
  Client/Client.Qt/Widgets/ChatWidget.cpp
  Client/Client.Qt/Widgets/ChatWidget.hpp
  Client/Client.Qt/Widgets/ComboBox.cpp
  Client/Client.Qt/Widgets/ComboBox.hpp
  Client/Client.Qt/Widgets/InputFields.cpp
  Client/Client.Qt/Widgets/InputFields.hpp
  Client/Client.Qt/Widgets/Label.cpp
  Client/Client.Qt/Widgets/Label.hpp
  Client/Client.Qt/Widgets/ListWidget.cpp
  Client/Client.Qt/Widgets/ListWidget.hpp
  Client/Client.Qt/Widgets/LoadingSpinner.hpp
  Client/Client.Qt/Widgets/LogoWidget.cpp
  Client/Client.Qt/Widgets/LogoWidget.hpp
  Client/Client.Qt/Widgets/Menu.cpp
  Client/Client.Qt/Widgets/Menu.hpp
  Client/Client.Qt/Widgets/MenuItem.hpp
  Client/Client.Qt/Widgets/MessageWidget.cpp
  Client/Client.Qt/Widgets/MessageWidget.hpp
  Client/Client.Qt/Widgets/Page.cpp
  Client/Client.Qt/Widgets/Page.hpp
  Client/Client.Qt/Widgets/PopupWidget.cpp
  Client/Client.Qt/Widgets/ReactionLayout.cpp
  Client/Client.Qt/Widgets/ReactionLayout.hpp
  Client/Client.Qt/Widgets/ScrollArea.cpp
  Client/Client.Qt/Widgets/ScrollArea.hpp
  Client/Client.Qt/Widgets/TextEdit.cpp
  Client/Client.Qt/Widgets/TextEdit.hpp
  Client/Client.Qt/Widgets/TitleWidget.cpp
  Client/Client.Qt/Widgets/TitleWidget.hpp
Labels: documentation, enhancement, Front

#363 Message Receiving
  Client/Client.Qt/ConnectionManager.cpp
  Client/Client.Qt/Widgets/ChatHistory.cpp
  Client/Client.Qt/Widgets/ChatHistory.hpp
  Client/Client.Qt/Widgets/ChatWidget.cpp
  Client/Client.Qt/Widgets/ChatWidget.hpp
  Client/Client.Qt/Widgets/MessageWidget.cpp
Labels: Front

#366 SenderID fix
  Network/Public/Include/Network/Primitives.hpp
Labels: bug, Back

#373 Delete user message
  Client/Client.CLI/App.cpp
  Client/Client.CLI/App.hpp
  Client/Client.CLI/MainClient.cpp
  Client/Client.Core/Client.Core.Static/Client.cpp
  Client/Client.Core/Client.Core.Static/Client.hpp
  Client/Client.Qt/ConnectionManager.cpp
  Client/Client.Qt/ConnectionManager.hpp
  Client/Client.Qt/Widgets/MessageWidget.cpp
  DataAccess/DataAccess.Postgre/DataBaseOptions.hpp
  DataAccess/DataAccess.Postgre/PostgreRepository.cpp
  DataAccess/DataAccess.Postgre/PostgreRepository.hpp
  DataAccess/Public/Include/DataAccess/IRepository.hpp
  Network/Public/Include/Network/Connection.hpp
  Network/Public/Include/Network/Message.hpp
  Network/Public/Include/Network/Primitives.hpp
  Network/Public/Include/Network/SerializationHandler.hpp
  Server/Server.Core/Server.Core.Static/Server.cpp
  Utility/Utility.Public/Include/Utility/Utility.hpp
Labels: Back
