Repository f1nal3/Juniorgram, pull requests merged in 2021-09, with the labels that each got.

#402 Create new targets for future repository system #396
  DataAccess/CMakeLists.txt
  DataAccess/DataAccess.Repository/CMakeLists.txt
  DataAccess/DataAccess.Repository/Client/CMakeLists.txt
  DataAccess/DataAccess.Repository/Client/ClientRepositoryContainer.hpp
  DataAccess/DataAccess.Repository/Client/Repositories.hpp
  DataAccess/DataAccess.Repository/Public/AbstarctRepositoryContainer.hpp
  DataAccess/DataAccess.Repository/Public/CMakeLists.txt
  DataAccess/DataAccess.Repository/Public/IRepositories.hpp
  DataAccess/DataAccess.Repository/Server/CMakeLists.txt
  DataAccess/DataAccess.Repository/Server/Repositories.hpp
  DataAccess/DataAccess.Repository/Server/ServerRepositoryContainer.hpp
Labels: enhancement, Back, Epic

#394 Back/reply message type
  Client/Client.Core/Client.Core.Static/Client.cpp
  Client/Client.Core/Client.Core.Static/Client.hpp
  Client/Client.Qt/ConnectionManager.cpp
  Client/Client.Qt/ConnectionManager.hpp
  Client/Client.Qt/Widgets/ChatHistory.cpp
  Client/Client.Qt/Widgets/ChatHistory.hpp
  Client/Client.Qt/Widgets/ChatWidget.cpp
  Client/Client.Qt/Widgets/ChatWidget.hpp
  Client/Client.Qt/Widgets/MessageWidget.hpp
  Client/Client.Qt/Widgets/ReplyMessageWidget.cpp
  Client/Client.Qt/Widgets/ReplyMessageWidget.hpp
  Client/Client.Qt/Widgets/ReplyWidget.cpp
  Client/Client.Qt/Widgets/ReplyWidget.hpp
  DataAccess/DataAccess.Postgre/PostgreRepository.cpp
  DataAccess/DataAccess.Postgre/PostgreRepository.hpp
  DataAccess/Public/Include/DataAccess/IRepository.hpp
  Network/Public/Include/Network/Message.hpp
  Network/Public/Include/Network/Primitives.hpp
  Network/Public/Include/Network/SerializationHandler.hpp
  Server/Server.Core/Server.Core.Static/Server.cpp
  Utility/SQL/Database_Scheme.sql
  Utility/Utility.Public/Include/Utility/Utility.hpp
Labels: enhancement, Back

#408 Client documentation
  Client/Client.Qt/Widgets/ChatWidget.hpp
  Client/Client.Qt/Widgets/MessageWidget.hpp
  Client/Client.Qt/Widgets/TextEdit.hpp
Labels: documentation

#409 New Repository system implementation
  DataAccess/DataAccess.Postgre/1PostgreRepository.cpp
  DataAccess/DataAccess.Postgre/1PostgreRepository.hpp
  DataAccess/DataAccess.Postgre/CMakeLists.txt
  DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
  DataAccess/DataAccess.Postgre/PostgreRepositories.hpp
  DataAccess/DataAccess.Postgre/PostgreRepositoryContainer.hpp
  DataAccess/DataAccess.Postgre/PostgreTable.hpp
  DataAccess/DataAccess.Postgre/ServerRepositories.hpp
  DataAccess/DataAccess.Postgre/ServerRepositoryContainer.hpp
  DataAccess/DataAccess.Postgre/UsersAmountFinder.hpp
  DataAccess/DataAccess.SQLite/CMakeLists.txt
  DataAccess/DataAccess.SQLite/ClientRepositoryContainer.hpp
  DataAccess/DataAccess.SQLite/LiteRepositories.cpp
  DataAccess/DataAccess.SQLite/LiteRepositories.hpp
  DataAccess/DataAccess.SQLite/LiteRepositoryContainer.hpp
  DataAccess/DataAccess.SQLite/LiteTable.hpp
  DataAccess/DataAccess.Test/RepositoryFunctionsTest.cpp
  DataAccess/DataAccess.Test/TestPostgreRepository.hpp
  DataAccess/Public/CMakeLists.txt
  DataAccess/Public/Include/DataAccess/AbstarctRepositoryContainer.hpp
  DataAccess/Public/Include/DataAccess/IAdapter.hpp
  DataAccess/Public/Include/DataAccess/IClientRepositories.hpp
  DataAccess/Public/Include/DataAccess/IMasterRepository.hpp
  DataAccess/Public/Include/DataAccess/IServerRepositories.hpp
  DataAccess/Public/Include/DataAccess/QueryBuilder.hpp
  Server/Server.Core/Server.Core.Static/Server.cpp
  Server/Server.Core/Server.Core.Static/Server.hpp
  Server/Server.Exec/MainServer.cpp
Labels: enhancement, Back

#410 [Front] Channel subscription
  Client/Client.Core/Client.Core.Static/Client.cpp
  Client/Client.Core/Client.Core.Static/Client.hpp
  Client/Client.Qt/Pages/ChannelListPage.cpp
  Client/Client.Qt/Widgets/ChatWidget.hpp
  Network/Public/Include/Network/Primitives.hpp
Labels: Front

#416 Back/server Channel creating
  Client/Client.Core/Client.Core.Static/Client.cpp
  Client/Client.Core/Client.Core.Static/Client.hpp
  Client/Client.Qt/ConnectionManager.cpp
  Client/Client.Qt/ConnectionManager.hpp
  DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
  DataAccess/DataAccess.Postgre/PostgreRepositories.hpp
  DataAccess/Public/Include/DataAccess/IServerRepositories.hpp
  Network/Public/Include/Network/Message.hpp
  Network/Public/Include/Network/SerializationHandler.hpp
  Server/Server.Core/Server.Core.Static/Server.cpp
  Utility/Utility.Public/Include/Utility/Utility.hpp
Labels: enhancement, Back

#418 Back/server Channel deleting
  Client/Client.Core/Client.Core.Static/Client.cpp
  Client/Client.Core/Client.Core.Static/Client.hpp
  Client/Client.Qt/ConnectionManager.cpp
  Client/Client.Qt/ConnectionManager.hpp
  DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
  DataAccess/DataAccess.Postgre/PostgreRepositories.hpp
  DataAccess/Public/Include/DataAccess/IServerRepositories.hpp
  Network/Public/Include/Network/Message.hpp
  Network/Public/Include/Network/Primitives.hpp
  Network/Public/Include/Network/SerializationHandler.hpp
  Server/Server.Core/Server.Core.Static/Server.cpp
  Utility/Utility.Public/Include/Utility/Utility.hpp
Labels: Back
