Repository f1nal3/Juniorgram, pull requests merged in 2021-07, with the labels that each got.

#250 Front refactoring
  Client/Client.Qt/CMakeLists.txt
  Client/Client.Qt/MainWidget.cpp
  Client/Client.Qt/MainWidget.hpp
  Client/Client.Qt/Widgets/AbstractButton.cpp
  Client/Client.Qt/Widgets/AbstractButton.hpp
  Client/Client.Qt/Widgets/BioButton.cpp
  Client/Client.Qt/Widgets/ChannelListWidget.cpp
  Client/Client.Qt/Widgets/ChannelListWidget.hpp
  Client/Client.Qt/Widgets/ChannelListWindow.cpp
  Client/Client.Qt/Widgets/ChannelListWindow.hpp
  Client/Client.Qt/Widgets/ComboBox.cpp
  Client/Client.Qt/Widgets/FlatButton.cpp
  Client/Client.Qt/Widgets/FlatButton.hpp
  Client/Client.Qt/Widgets/InputFields.cpp
  Client/Client.Qt/Widgets/InputFields.hpp
  Client/Client.Qt/Widgets/LogoWidget.cpp
  Client/Client.Qt/Widgets/LogoWidget.hpp
  Client/Client.Qt/Widgets/Menu.cpp
  Client/Client.Qt/Widgets/Menu.hpp
  Client/Client.Qt/Widgets/MenuItem.cpp
  Client/Client.Qt/Widgets/MenuItem.hpp
  Client/Client.Qt/Widgets/MessageWidget.cpp
  Client/Client.Qt/Widgets/MessageWidget.hpp
  Client/Client.Qt/Widgets/PopupWidget.cpp
  Client/Client.Qt/Widgets/PopupWidget.hpp
  Client/Client.Qt/Widgets/TextEdit.cpp
  Client/Client.Qt/Widgets/TextEdit.hpp
  Client/Client.Qt/registration.cpp
Labels: Front

#267 Front Urgent Fix
  Client/Client.Qt/Widgets/ChannelListWidget.cpp
  Client/Client.Qt/Widgets/ChannelListWidget.hpp
  Client/Client.Qt/Widgets/ChannelListWindow.hpp
Labels: Front, bug

#268 Front change chat window
  Client/Client.Qt/CMakeLists.txt
  Client/Client.Qt/ChatWindow.cpp
  Client/Client.Qt/ChatWindow.hpp
  Client/Client.Qt/Widgets/ChatWidget.cpp
  Client/Client.Qt/Widgets/ChatWidget.hpp
  Client/Client.Qt/Widgets/MessageWidget.cpp
  Client/Client.Qt/Widgets/MessageWidget.hpp
  Client/Client.Qt/Widgets/TextEdit.cpp
  Client/Client.Qt/Widgets/TextEdit.hpp
Labels: Front

#264 Data validation
  Client/Client.CLI/App.cpp
  Client/Client.Core/Client.Core.Static/CMakeLists.txt
  Client/Client.Core/Client.Core.Static/Client.cpp
  Client/Client.Qt/ConnectionManager.hpp
  Client/Client.Qt/registration.cpp
  Client/Client.Qt/registration.hpp
  DataAccess/DataAccess.Static/RepositoryUnits.cpp
  DataAccess/DataAccess.Static/RepositoryUnits.hpp
  Network/Public/Include/Network/Message.hpp
  Network/Public/Include/Network/Primitives.hpp
  Server/Server.Core/Server.Core.Static/Server.cpp
  Utility/Utility.Public/CMakeLists.txt
  Utility/Utility.Public/Include/Utility/SerializationHandler.hpp
  Utility/Utility.Public/Include/Utility/UserDataValidation.hpp
  Utility/Utility.Public/Include/Utility/Utility.hpp
  Utility/Utility.Static/CMakeLists.txt
  Utility/Utility.Static/Cryptography.cpp
  Utility/Utility.Static/Cryptography.hpp
Labels: Back

#258 Utility refactoring #224
  Client/Client.CLI/App.cpp
  Network/Network.Test/BinarySerializeTest.cpp
  Network/Network.Test/CMakeLists.txt
  Network/Public/CMakeLists.txt
  Network/Public/Include/Network/CompressionHandler.hpp
  Network/Public/Include/Network/Connection.hpp
  Network/Public/Include/Network/EncryptionHandler.hpp
  Network/Public/Include/Network/Handler.hpp
  Network/Public/Include/Network/SerializationHandler.hpp
  Network/Public/Include/Network/YasSerializer.hpp
  Utility/Utility.Public/CMakeLists.txt
  Utility/Utility.Public/Include/Utility/Exception.hpp
  Utility/Utility.Public/Include/Utility/SQLUtility.hpp
  Utility/Utility.Public/Include/Utility/Utility.hpp
  Utility/Utility.Public/Include/Utility/WarningSuppression.hpp
  Utility/Utility.Static/JsonSerializer.cpp
  Utility/Utility.Static/JsonSerializer.hpp
  Utility/Utility.Static/Task.hpp
  Utility/Utility.Static/TaskManager.hpp
  Utility/Utility.Test/CMakeLists.txt
  Utility/Utility.Test/JsonSerializeTest.cpp
Labels: Technical debt

#269 Back/registration tests
  Client/Client.Qt/ConnectionManager.hpp
  DataAccess/DataAccess.Static/CMakeLists.txt
  DataAccess/DataAccess.Static/DataBaseOptions.hpp
  DataAccess/DataAccess.Static/PostgreAdapter.hpp
  DataAccess/DataAccess.Static/RepositoryUnits.cpp
  DataAccess/DataAccess.Static/RepositoryUnits.hpp
  DataAccess/DataAccess.Static/UsersAmountFinder.cpp
  DataAccess/DataAccess.Static/UsersAmountFinder.hpp
  DataAccess/DataAccess.Test/CMakeLists.txt
  DataAccess/DataAccess.Test/DataAccessTest.cpp
  DataAccess/DataAccess.Test/RepositoryUnitsTest.cpp
  DataAccess/DataAccess.Test/TestRegistrationUnit.hpp
  DataAccess/DataAccess.Test/TestUsersAmountFinder.hpp
  Server/Server.Core/Server.Core.Static/Server.cpp
Labels: Back

#273 Chat history
  .clang-format
  Client/Client.Core/Client.Core.Static/Client.cpp
  Client/Client.Qt/CMakeLists.txt
  Client/Client.Qt/ChatWindow.cpp
  Client/Client.Qt/ChatWindow.hpp
  Client/Client.Qt/Style/Palette.cpp
  Client/Client.Qt/Style/Palette.hpp
  Client/Client.Qt/Style/StyleBasic.cpp
  Client/Client.Qt/Style/StyleBasic.hpp
  Client/Client.Qt/Style/StyleColor.hpp
  Client/Client.Qt/Widgets/ChannelListWidget.cpp
  Client/Client.Qt/Widgets/ChannelListWidget.hpp
  Client/Client.Qt/Widgets/ChannelListWindow.cpp
  Client/Client.Qt/Widgets/ChannelListWindow.hpp
  Client/Client.Qt/Widgets/ChatHistory.cpp
  Client/Client.Qt/Widgets/ChatHistory.hpp
  Client/Client.Qt/Widgets/ChatWidget.cpp
  Client/Client.Qt/Widgets/ChatWidget.hpp
  Client/Client.Qt/Widgets/InputFields.cpp
  Client/Client.Qt/Widgets/InputFields.hpp
  Client/Client.Qt/Widgets/MessageWidget.cpp
  Client/Client.Qt/Widgets/MessageWidget.hpp
  Client/Client.Qt/Widgets/ScrollArea.cpp
  Client/Client.Qt/Widgets/ScrollArea.hpp
  Client/Client.Qt/Widgets/TextEdit.cpp
  Client/Client.Qt/Widgets/TextEdit.hpp
Labels: Front, enhancement

#294 data validation & fixing clang format & fix bug with 2 fields db connections
  .clang-format
  Client/Client.CLI/MainClient.cpp
  Client/Client.Core/Client.Core.Static/ServerInfo.hpp
  DataAccess/DataAccess.Static/PostgreAdapter.hpp
Labels: Back, Front

#301 Front message del
  Client/Client.Core/Client.Core.Static/Client.cpp
  Client/Client.Core/Client.Core.Static/Client.hpp
  Client/Client.Qt/ChatWindow.hpp
  Client/Client.Qt/ConnectionManager.hpp
  Client/Client.Qt/Widgets/ChatHistory.cpp
  Client/Client.Qt/Widgets/ChatHistory.hpp
  Client/Client.Qt/Widgets/ChatWidget.hpp
  Client/Client.Qt/Widgets/MessageWidget.cpp
  Client/Client.Qt/Widgets/MessageWidget.hpp
  Network/Public/Include/Network/Message.hpp
  Network/Public/Include/Network/Primitives.hpp
Labels: Front, enhancement

#303 Move registration to postgre repository
  DataAccess/DataAccess.Postgre/CMakeLists.txt
  DataAccess/DataAccess.Postgre/PostgreRepository.cpp
  DataAccess/DataAccess.Postgre/PostgreRepository.hpp
  DataAccess/DataAccess.Postgre/QueryBuilder.hpp
  DataAccess/DataAccess.Postgre/RepositoryUnits.cpp
  DataAccess/DataAccess.Postgre/RepositoryUnits.hpp
  DataAccess/DataAccess.Postgre/SQLStatements.hpp
  DataAccess/DataAccess.Test/CMakeLists.txt
  DataAccess/DataAccess.Test/RepositoryFunctionsTest.cpp
  DataAccess/DataAccess.Test/TestPostgreRepository.hpp
  DataAccess/DataAccess.Test/TestRegistrationUnit.hpp
  DataAccess/Public/Include/DataAccess/IRepository.hpp
  Server/Server.Core/Server.Core.Static/Server.cpp
  Utility/Utility.Public/Include/Utility/Utility.hpp
Labels: Back, Technical debt

#317 Fix bag with creation chat widget
  Client/Client.Qt/ChatWindow.cpp
Labels: Front, bug

#313 Fixing the sequence of client connection and window creation
  Client/Client.Core/Client.Core.Static/Client.cpp
  Client/Client.Qt/Application.cpp
  Client/Client.Qt/Widgets/ChannelListWidget.cpp
  Client/Client.Qt/Widgets/ChannelListWindow.cpp
Labels: Front, bug

#318 PostgreRepository documentation
  DataAccess/DataAccess.Postgre/PostgreAdapter.hpp
  DataAccess/DataAccess.Postgre/UsersAmountFinder.hpp
  DataAccess/DataAccess.SQLite/LiteAdapter.hpp
  DataAccess/DataAccess.Test/TestPostgreRepository.hpp
  DataAccess/DataAccess.Test/TestUsersAmountFinder.hpp
Labels: documentation
