Repository f1nal3/Juniorgram, pull requests merged in 2022-03, with the labels that each got.

#493 Task 443: rename realdb variable
  Server/Server.Core/Server.Core.Static/ArgumentParser.cpp
  Server/Server.Core/Server.Core.Static/ArgumentParser.hpp
  Server/Server.Core/Server.Core.Static/KeysValidator.hpp
  Server/Server.Core/Server.Core.Static/Server.hpp
  Server/Server.Test/ArgumentParserTests.cpp
Labels: enhancement

#502 Change date representation in database
  Client/Client.Core/Client.Core.Static/Client.cpp
  DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
  Network/Public/Include/Network/Primitives.hpp
  Utility/Utility.Public/Include/Utility/Utility.hpp
Labels: bug, Back

#505 Dev Enviroment improvement
  .gitignore
  Base/Logger/Logger.Static/FileLogger.cpp
  Base/Logger/Logger.Static/FileLogger.hpp
  Base/Logger/Public/CMakeLists.txt
  CMakeLists.txt
  DataAccess/Public/CMakeLists.txt
  Network/Public/CMakeLists.txt
  Network/Public/Include/Network/Handler.hpp
  Server/Server.Core/Server.Core.Static/Server.cpp
  Server/Server.Exec/CMakeLists.txt
  Utility/Utility.Public/CMakeLists.txt
  cmake/CMakeConfig.cmake
  cmake/Ccache.cmake
  cmake/ConanModule.cmake
  cmake/Warnings.cmake
Labels: enhancement, infrastructure
