Repository f1nal3/Juniorgram, pull requests merged in 2022-07, with the labels that each got.

#573 514 primitives from network to base
  Base/CMakeLists.txt
  Base/Models/CMakeLists.txt
  Base/Models/Public/CMakeLists.txt
  Base/Models/Public/Include/Models/Primitives.hpp
  Client/Client.CLI/App.cpp
  Client/Client.CLI/App.hpp
  Client/Client.CLI/MainClient.cpp
  Client/Client.Core/Client.Core.Static/CMakeLists.txt
  Client/Client.Core/Client.Core.Static/Client.cpp
  Client/Client.Core/Client.Core.Static/Client.hpp
  Client/Client.Qt/ConnectionManager.cpp
  Client/Client.Qt/ConnectionManager.hpp
  Client/Client.Qt/Pages/ChannelCreationPage.hpp
  Client/Client.Qt/Pages/ChannelListPage.cpp
  Client/Client.Qt/Pages/ChannelListPage.hpp
  Client/Client.Qt/Pages/ChatPage.cpp
  Client/Client.Qt/Widgets/ChannelBar.cpp
  Client/Client.Qt/Widgets/ChannelBar.hpp
  Client/Client.Qt/Widgets/ChatHistory.cpp
  Client/Client.Qt/Widgets/ChatHistory.hpp
  Client/Client.Qt/Widgets/ChatWidget.cpp
  Client/Client.Qt/Widgets/ChatWidget.hpp
  DataAccess/DataAccess.Debug/FileRepository.cpp
  DataAccess/DataAccess.Debug/FileRepository.hpp
  DataAccess/DataAccess.Postgre/CMakeLists.txt
  DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
  DataAccess/DataAccess.Postgre/PostgreRepositories.hpp
  DataAccess/DataAccess.Postgre/UsersAmountFinder.cpp
  DataAccess/DataAccess.Postgre/UsersAmountFinder.hpp
  DataAccess/DataAccess.Test/PostgreRepositoriesTest.cpp
  DataAccess/DataAccess.Test/UsersAmountFinderTest.cpp
  DataAccess/Public/CMakeLists.txt
  DataAccess/Public/Include/DataAccess/IRepository.hpp
  DataAccess/Public/Include/DataAccess/IServerRepositories.hpp
  Network/Network.Test/BinarySerializeTest.cpp
  Network/Public/CMakeLists.txt
  Network/Public/Include/Network/SerializationHandler.hpp
  Network/Public/Include/Network/YasSerializer.hpp
  Server/Server.Core/Server.Core.Static/Server.cpp
Labels: enhancement

#582 Fixing bad output from Logger
  Base/Logger/Logger.Static/CMakeLists.txt
  Base/Logger/Logger.Static/FileLogger.cpp
  Base/Logger/Logger.Static/FileLogger.hpp
  Base/Logger/Logger.Test/FileLoggerTests.cpp
  DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
  DataAccess/Public/Include/DataAccess/SQLStatements.hpp
Labels: bug, Back

#587 changed past namespace to new one in qRegisterMetaType methods
  Client/Client.Qt/ConnectionManager.cpp
Labels: bug
