Repository f1nal3/Juniorgram, pull requests merged in 2022-05, with the labels that each got.

#529 Data access technical debt
  DataAccess/DataAccess.Debug/FileDB.cpp
  DataAccess/DataAccess.Debug/FileRepository.cpp
  DataAccess/DataAccess.Debug/FileRepository.hpp
  DataAccess/DataAccess.Postgre/PostgreAdapter.cpp
  DataAccess/DataAccess.Postgre/PostgreAdapter.hpp
  DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
  DataAccess/DataAccess.Postgre/PostgreRepositories.hpp
  DataAccess/DataAccess.Postgre/PostgreRepositoryContainer.hpp
  DataAccess/DataAccess.Postgre/PostgreRepositoryManager.hpp
  DataAccess/DataAccess.Postgre/PostgreTable.hpp
  DataAccess/DataAccess.Postgre/UsersAmountFinder.cpp
  DataAccess/DataAccess.Postgre/UsersAmountFinder.hpp
  DataAccess/DataAccess.SQLite/LiteAdapter.cpp
  DataAccess/DataAccess.SQLite/LiteAdapter.hpp
  DataAccess/DataAccess.SQLite/LiteRepositories.cpp
  DataAccess/DataAccess.SQLite/LiteRepositories.hpp
  DataAccess/DataAccess.SQLite/LiteRepositoryContainer.hpp
  DataAccess/DataAccess.SQLite/LiteTable.hpp
  DataAccess/Public/Include/DataAccess/AbstractRepositoryContainer.hpp
  DataAccess/Public/Include/DataAccess/IAdapter.hpp
  DataAccess/Public/Include/DataAccess/IClientRepositories.hpp
  DataAccess/Public/Include/DataAccess/IMasterRepository.hpp
  DataAccess/Public/Include/DataAccess/IRepository.hpp
  DataAccess/Public/Include/DataAccess/IServerRepositories.hpp
  DataAccess/Public/Include/DataAccess/QueryBuilder.hpp
  DataAccess/Public/Include/DataAccess/SQLStatements.hpp
Labels: enhancement, Technical debt

#547 Refactoring
  Base/Crypto/Crypto.Static/Cryptography.cpp
  Base/Crypto/Crypto.Static/Cryptography.hpp
  Base/Logger/Logger.Static/FileLogger.cpp
  Base/Logger/Logger.Static/FileLogger.hpp
  Base/Logger/Logger.Test/CMakeLists.txt
  Base/Logger/Logger.Test/FileLoggerTests.cpp
  Base/Logger/Public/Include/Logger/ILogger.hpp
  Network/Public/Include/Network/Message.hpp
  Network/Public/Include/Network/Primitives.hpp
  Utility/Utility.Public/Include/Utility/Exception.hpp
  Utility/Utility.Public/Include/Utility/Utility.hpp
  Utility/Utility.Public/Include/Utility/UtilityTime.hpp
  Utility/Utility.Test/ExceptionTest.cpp
  cmake/ConanModule.cmake
  cmake/Warnings.cmake
Labels: Technical debt

#536 Fixing some smells
  Client/Client.Core/Client.Core.Static/Client.cpp
  Network/Public/Include/Network/Message.hpp
  Utility/Utility.Public/Include/Utility/UtilityTime.hpp
Labels: bug, Back

#548 turn off coverage analisys for Cleint.Qt
  Client/CMakeLists.txt
Labels: infrastructure

#551 Exclude from coverage list all tests
  sonar-project.properties
Labels: enhancement

#550 Test coverare
  .gitignore
  Base/Crypto/CMakeLists.txt
  Base/Crypto/Crypto.Static/CMakeLists.txt
  Base/Crypto/Crypto.Static/Cryptography.cpp
  Base/Crypto/Crypto.Static/Cryptography.hpp
  Base/Crypto/Crypto.Test/CMakeLists.txt
  Base/Crypto/Crypto.Test/CryptoTests.cpp
  Client/Client.Core/Client.Core.Static/CMakeLists.txt
  Utility/Utility.Test/ExceptionTest.cpp
Labels: enhancement, Technical debt, tests

#528 InterfaceClassPopUp_Backup
  Client/Client.Qt/CMakeLists.txt
  Client/Client.Qt/Pages/RegistrationPage.cpp
  Client/Client.Qt/Pages/RegistrationPage.hpp
  Client/Client.Qt/Widgets/AbstractMessageWidget.cpp
  Client/Client.Qt/Widgets/AbstractPopupMessage.cpp
  Client/Client.Qt/Widgets/AbstractPopupMessage.hpp
  Client/Client.Qt/Widgets/PopupMessage.cpp
  Client/Client.Qt/Widgets/PopupMessage.hpp
  Client/Client.Qt/Widgets/PopupSystemMessage.cpp
  Client/Client.Qt/Widgets/PopupSystemMessage.hpp
Labels: enhancement, Front

#554 Server technical debt
  Server/Server.Core/Server.Core.Static/ArgumentParser.cpp
  Server/Server.Core/Server.Core.Static/ArgumentParser.hpp
  Server/Server.Core/Server.Core.Static/KeysValidator.hpp
  Server/Server.Core/Server.Core.Static/Server.cpp
  Server/Server.Core/Server.Core.Static/Server.hpp
  Server/Server.Exec/MainServer.cpp
Labels: enhancement, Back, Technical debt

#556 Increase conan version for windows
  .github/workflows/Windows Build.yml
Labels: infrastructure
