Repository f1nal3/Juniorgram, pull requests merged in 2022-01, with the labels that each got.

#472 Catch_fix
  Base/Logger/Logger.Test/FileLoggerTests.cpp
  Client/Client.Core/Client.Core.Test/ClientCoreTest.cpp
  DataAccess/DataAccess.Test/DataAccessTest.cpp
  DataAccess/DataAccess.Test/FileDBTest.cpp
  Network/Network.Test/BinarySerializeTest.cpp
  Network/Network.Test/TimestampTest.cpp
  Server/Server.Test/ArgumentParserTests.cpp
  Test/Precompiled/Catch2/CMakeLists.txt
  Test/Precompiled/Catch2/CatchDummyTest.cpp
  Test/Precompiled/Catch2/CatchMainConfig.cpp
  Utility/Utility.Test/ExceptionTest.cpp
Labels: bug

#475 Code duplication
  Client/Client.Qt/CMakeLists.txt
  Client/Client.Qt/Widgets/AbstractMessageWidget.cpp
  Client/Client.Qt/Widgets/AbstractMessageWidget.hpp
  Client/Client.Qt/Widgets/MessageWidget.cpp
  Client/Client.Qt/Widgets/MessageWidget.hpp
  Client/Client.Qt/Widgets/ReplyMessageWidget.cpp
  Client/Client.Qt/Widgets/ReplyMessageWidget.hpp
Labels: Front

#474 CMakeLists variables correcting
  Client/Client.Qt/CMakeLists.txt
Labels: bug, Front

#471 reorganized try-catch blocks in Server
  Server/Server.Core/Server.Core.Static/Server.cpp
  Server/Server.Core/Server.Core.Static/Server.hpp
  Server/Server.Exec/MainServer.cpp
Labels: Technical debt

#478 fixed conversion problem
  DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
Labels: bug
