Repository f1nal3/Juniorgram, pull requests merged in 2022-06, with the labels that each got.

#561 Fixing brackets in switch cycle
  Server/Server.Core/Server.Core.Static/Server.cpp
Labels: Technical debt

#512 Task 496: Added draft AbstractPopupWidget
  Client/Client.Qt/CMakeLists.txt
  Client/Client.Qt/Widgets/AbstractDropDownMenu.cpp
  Client/Client.Qt/Widgets/AbstractDropDownMenu.hpp
  Client/Client.Qt/Widgets/DropDownMenu.cpp
  Client/Client.Qt/Widgets/DropDownMenu.hpp
  Client/Client.Qt/Widgets/TitleWidget.cpp
  Client/Client.Qt/Widgets/TitleWidget.hpp
Labels: Front

#560 Improving debugging experience by .bat files
  Docs/Improved debugging.md
Labels: documentation, enhancement

#570 Fixing DB time conversion
  DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
Labels: bug

#571 No task: a couple of small changes.
  .gitignore
  Utility/Utility.Public/Include/Utility/UserDataValidation.hpp
Labels: Front, Back

#565 "Utility" test coverage
  Utility/Utility.Public/Include/Utility/Exception.hpp
  Utility/Utility.Public/Include/Utility/UserDataValidation.hpp
  Utility/Utility.Public/Include/Utility/Utility.hpp
  Utility/Utility.Test/CMakeLists.txt
  Utility/Utility.Test/ExceptionTest.cpp
  Utility/Utility.Test/UserDataValidationTest.cpp
  Utility/Utility.Test/UtilityTest.cpp
  Utility/Utility.Test/UtilityTimeTest.cpp
Labels: infrastructure, Technical debt

#553 DataAccess test debt
  DataAccess/DataAccess.Postgre/PostgreAdapter.cpp
  DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
  DataAccess/DataAccess.Postgre/PostgreRepositories.hpp
  DataAccess/DataAccess.Postgre/PostgreRepositoryManager.hpp
  DataAccess/DataAccess.Test/AbstractRepositoryContainerTest.cpp
  DataAccess/DataAccess.Test/CMakeLists.txt
  DataAccess/DataAccess.Test/DataAccessTest.cpp
  DataAccess/DataAccess.Test/FileDBTest.cpp
  DataAccess/DataAccess.Test/PostgreAdapterTest.cpp
  DataAccess/DataAccess.Test/PostgreRepositoriesContainerTest.cpp
  DataAccess/DataAccess.Test/PostgreRepositoriesTest.cpp
  DataAccess/DataAccess.Test/PostgreRepositoryManagerTest.cpp
  DataAccess/DataAccess.Test/PostgreTableTest.cpp
  DataAccess/DataAccess.Test/QueryBuilderTest.cpp
  DataAccess/DataAccess.Test/RepositoryFunctionsTest.cpp
  DataAccess/DataAccess.Test/TestPostgreRepository.hpp
  DataAccess/DataAccess.Test/TestUsersAmountFinder.hpp
  DataAccess/DataAccess.Test/UsersAmountFinderTest.cpp
Labels: Technical debt, tests
