Repository f1nal3/Juniorgram, pull requests merged in 2022-08, with the labels that each got.

#597 Changing of timestamp
  Base/Logger/Logger.Static/FileLogger.cpp
  Base/Logger/Logger.Static/FileLogger.hpp
Labels: bug, Back

#591 Refactoring of PGRepositoryManager
  DataAccess/DataAccess.Postgre/PostgreRepositoryManager.hpp
  DataAccess/DataAccess.Test/PostgreRepositoryManagerTest.cpp
  DataAccess/Public/CMakeLists.txt
  DataAccess/Public/Include/DataAccess/AbstractRepositoryManager.hpp
  DataAccess/Public/Include/DataAccess/FutureResult.hpp
  DataAccess/Public/Include/DataAccess/RepositoryRequest.hpp
Labels: enhancement, Back, Investigation

#588 585 SafeQueue from Network to Utility
  Base/Logger/Logger.Static/CMakeLists.txt
  Base/Logger/Logger.Static/FileLogger.hpp
  Client/Client.Core/Client.Core.Static/CMakeLists.txt
  Client/Client.Core/Client.Core.Static/Client.hpp
  Network/Public/CMakeLists.txt
  Network/Public/Include/Network/Connection.hpp
  Network/Public/Include/Network/SafeQueue.hpp
  Server/Server.Core/Server.Core.Static/Server.hpp
  Utility/Utility.Public/CMakeLists.txt
  Utility/Utility.Public/Include/Utility/SafeQueue.hpp
Labels: enhancement

#606 Extending the PostgreQuery documentation
  DataAccess/DataAccess.Postgre/PostgreQuery.hpp
Labels: documentation, Back

#592 Task 516: Moved reactionNames vector from PostgreRepositories to Base
  Base/Models/Public/Include/Models/Primitives.hpp
  DataAccess/DataAccess.Postgre/PostgreRepositories.cpp
Labels: enhancement

#610 Adding edit types of messages in incoming message body method
  Network/Public/Include/Network/SerializationHandler.hpp
Labels: bug
